import type { Block, BlockCategory } from '@/types/hyperframes';

export const BLOCK_CATEGORIES: BlockCategory[] = [
  'social',
  'cinematic',
  'data-viz',
  'text',
  'transition',
  'overlay',
  'template',
];

export const BLOCKS: Block[] = [
  {
    id: 'social-instagram-story',
    name: 'Instagram Story',
    category: 'social',
    description: 'Full-screen vertical story format with text overlay',
    html: '<div class="block-instagram-story" data-start="0" data-duration="5" data-track-index="0"><div class="story-content"><h2 class="story-title">Your Title</h2><p class="story-text">Your message here</p></div></div>',
    css: '.block-instagram-story { width: 1080px; height: 1920px; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); display: flex; align-items: center; justify-content: center; } .story-content { text-align: center; color: white; } .story-title { font-size: 64px; font-weight: 700; margin-bottom: 24px; } .story-text { font-size: 32px; opacity: 0.9; }',
    thumbnail: '/blocks/instagram-story.png',
    tags: ['social', 'instagram', 'story', 'vertical'],
    author: 'HyperFrames',
  },
  {
    id: 'social-youtube-intro',
    name: 'YouTube Intro',
    category: 'social',
    description: 'Animated channel intro with logo and title',
    html: '<div class="block-youtube-intro" data-start="0" data-duration="6" data-track-index="0"><div class="intro-logo">🎬</div><h1 class="intro-title">Channel Name</h1><p class="intro-subtitle">Subscribe for more</p></div>',
    css: '.block-youtube-intro { width: 1920px; height: 1080px; background: #0a0a0a; display: flex; flex-direction: column; align-items: center; justify-content: center; color: white; } .intro-logo { font-size: 96px; margin-bottom: 32px; } .intro-title { font-size: 72px; font-weight: 800; margin-bottom: 16px; } .intro-subtitle { font-size: 28px; opacity: 0.7; }',
    thumbnail: '/blocks/youtube-intro.png',
    tags: ['social', 'youtube', 'intro', 'horizontal'],
    author: 'HyperFrames',
  },
  {
    id: 'social-tiktok-frame',
    name: 'TikTok Frame',
    category: 'social',
    description: 'Vertical video frame with caption overlay',
    html: '<div class="block-tiktok-frame" data-start="0" data-duration="4" data-track-index="0"><div class="tiktok-caption"><p>✨ Your caption here ✨</p></div></div>',
    css: '.block-tiktok-frame { width: 1080px; height: 1920px; background: #000; position: relative; } .tiktok-caption { position: absolute; bottom: 120px; left: 32px; right: 32px; color: white; font-size: 36px; text-shadow: 0 2px 8px rgba(0,0,0,0.8); }',
    thumbnail: '/blocks/tiktok-frame.png',
    tags: ['social', 'tiktok', 'vertical', 'caption'],
    author: 'HyperFrames',
  },
  {
    id: 'cinematic-title-card',
    name: 'Cinematic Title Card',
    category: 'cinematic',
    description: 'Elegant title card with fade-in animation',
    html: '<div class="block-cinematic-title" data-start="0" data-duration="4" data-track-index="0" data-ease="ease-in-out"><h1 class="film-title">TITLE</h1><div class="film-divider"></div><p class="film-subtitle">A Story</p></div>',
    css: '.block-cinematic-title { width: 1920px; height: 1080px; background: #000; display: flex; flex-direction: column; align-items: center; justify-content: center; color: #e8d5b7; font-family: serif; } .film-title { font-size: 96px; letter-spacing: 16px; margin-bottom: 24px; } .film-divider { width: 120px; height: 2px; background: #e8d5b7; margin-bottom: 24px; } .film-subtitle { font-size: 32px; letter-spacing: 8px; opacity: 0.8; }',
    thumbnail: '/blocks/cinematic-title.png',
    tags: ['cinematic', 'title', 'elegant', 'film'],
    author: 'HyperFrames',
  },
  {
    id: 'cinematic-lower-third',
    name: 'Lower Third',
    category: 'cinematic',
    description: 'Professional lower third name/title overlay',
    html: '<div class="block-lower-third" data-start="0" data-duration="3" data-track-index="1"><div class="lt-accent"></div><div class="lt-content"><h3 class="lt-name">John Doe</h3><p class="lt-role">Creative Director</p></div></div>',
    css: '.block-lower-third { position: absolute; bottom: 80px; left: 60px; display: flex; align-items: stretch; } .lt-accent { width: 6px; background: #8b5cf6; margin-right: 16px; } .lt-content { color: white; } .lt-name { font-size: 36px; font-weight: 700; margin: 0; } .lt-role { font-size: 20px; opacity: 0.8; margin: 4px 0 0; }',
    thumbnail: '/blocks/lower-third.png',
    tags: ['cinematic', 'lower-third', 'name', 'overlay'],
    author: 'HyperFrames',
  },
  {
    id: 'cinematic-end-credits',
    name: 'End Credits',
    category: 'cinematic',
    description: 'Scrolling end credits with role sections',
    html: '<div class="block-end-credits" data-start="0" data-duration="8" data-track-index="0"><div class="credit-section"><h3 class="credit-role">Directed By</h3><p class="credit-name">Jane Smith</p></div><div class="credit-section"><h3 class="credit-role">Produced By</h3><p class="credit-name">John Doe</p></div></div>',
    css: '.block-end-credits { width: 1920px; height: 1080px; background: #000; display: flex; flex-direction: column; align-items: center; justify-content: center; color: white; font-family: serif; } .credit-section { text-align: center; margin-bottom: 40px; } .credit-role { font-size: 20px; letter-spacing: 4px; opacity: 0.6; margin-bottom: 8px; } .credit-name { font-size: 36px; }',
    thumbnail: '/blocks/end-credits.png',
    tags: ['cinematic', 'credits', 'scroll', 'film'],
    author: 'HyperFrames',
  },
  {
    id: 'data-viz-bar-chart',
    name: 'Bar Chart',
    category: 'data-viz',
    description: 'Animated bar chart with labels',
    html: '<div class="block-bar-chart" data-start="0" data-duration="5" data-track-index="0"><div class="chart-bars"><div class="bar" style="--bar-height: 80%"><span class="bar-label">Q1</span></div><div class="bar" style="--bar-height: 60%"><span class="bar-label">Q2</span></div><div class="bar" style="--bar-height: 95%"><span class="bar-label">Q3</span></div><div class="bar" style="--bar-height: 70%"><span class="bar-label">Q4</span></div></div></div>',
    css: '.block-bar-chart { width: 1920px; height: 1080px; background: #111; display: flex; align-items: flex-end; justify-content: center; padding: 80px; } .chart-bars { display: flex; align-items: flex-end; gap: 40px; height: 600px; } .bar { width: 120px; height: var(--bar-height); background: linear-gradient(to top, #8b5cf6, #a78bfa); border-radius: 8px 8px 0 0; position: relative; } .bar-label { position: absolute; bottom: -32px; left: 50%; transform: translateX(-50%); color: white; font-size: 24px; }',
    thumbnail: '/blocks/bar-chart.png',
    tags: ['data-viz', 'chart', 'bar', 'animated'],
    author: 'HyperFrames',
  },
  {
    id: 'data-viz-stat-card',
    name: 'Stat Card',
    category: 'data-viz',
    description: 'Large number stat card with label',
    html: '<div class="block-stat-card" data-start="0" data-duration="3" data-track-index="0"><div class="stat-number">1,234</div><div class="stat-label">Total Users</div></div>',
    css: '.block-stat-card { width: 1920px; height: 1080px; background: #0a0a0a; display: flex; flex-direction: column; align-items: center; justify-content: center; color: white; } .stat-number { font-size: 144px; font-weight: 800; background: linear-gradient(135deg, #8b5cf6, #06b6d4); -webkit-background-clip: text; -webkit-text-fill-color: transparent; } .stat-label { font-size: 36px; opacity: 0.6; margin-top: 16px; letter-spacing: 4px; }',
    thumbnail: '/blocks/stat-card.png',
    tags: ['data-viz', 'stat', 'number', 'metric'],
    author: 'HyperFrames',
  },
  {
    id: 'text-heading-center',
    name: 'Centered Heading',
    category: 'text',
    description: 'Large centered heading with optional subtitle',
    html: '<div class="block-heading-center" data-start="0" data-duration="3" data-track-index="0"><h1 class="heading-main">Your Heading</h1><p class="heading-sub">Optional subtitle text</p></div>',
    css: '.block-heading-center { width: 1920px; height: 1080px; display: flex; flex-direction: column; align-items: center; justify-content: center; color: white; background: #09090b; } .heading-main { font-size: 80px; font-weight: 700; margin-bottom: 16px; } .heading-sub { font-size: 28px; opacity: 0.6; }',
    thumbnail: '/blocks/heading-center.png',
    tags: ['text', 'heading', 'title', 'center'],
    author: 'HyperFrames',
  },
  {
    id: 'text-quote-block',
    name: 'Quote Block',
    category: 'text',
    description: 'Stylized quotation with attribution',
    html: '<div class="block-quote" data-start="0" data-duration="4" data-track-index="0"><blockquote class="quote-text">"The best way to predict the future is to create it."</blockquote><p class="quote-author">— Peter Drucker</p></div>',
    css: '.block-quote { width: 1920px; height: 1080px; display: flex; flex-direction: column; align-items: center; justify-content: center; color: white; background: #09090b; padding: 120px; } .quote-text { font-size: 48px; font-style: italic; max-width: 1200px; text-align: center; line-height: 1.4; margin-bottom: 32px; } .quote-author { font-size: 24px; opacity: 0.6; }',
    thumbnail: '/blocks/quote-block.png',
    tags: ['text', 'quote', 'attribution', 'elegant'],
    author: 'HyperFrames',
  },
  {
    id: 'text-typewriter',
    name: 'Typewriter Effect',
    category: 'text',
    description: 'Text that appears character by character',
    html: '<div class="block-typewriter" data-start="0" data-duration="5" data-track-index="0"><p class="typewriter-text">Hello World. This text types itself.</p></div>',
    css: '.block-typewriter { width: 1920px; height: 1080px; display: flex; align-items: center; justify-content: center; background: #09090b; } .typewriter-text { color: #8b5cf6; font-size: 64px; font-family: monospace; overflow: hidden; white-space: nowrap; border-right: 4px solid #8b5cf6; animation: typing 3s steps(40) 1s 1 normal both, blink 0.75s step-end infinite; } @keyframes typing { from { width: 0; } to { width: 100%; } } @keyframes blink { from, to { border-color: transparent; } 50% { border-color: #8b5cf6; } }',
    thumbnail: '/blocks/typewriter.png',
    tags: ['text', 'typewriter', 'animation', 'retro'],
    author: 'HyperFrames',
  },
  {
    id: 'transition-fade-black',
    name: 'Fade to Black',
    category: 'transition',
    description: 'Classic fade through black transition',
    html: '<div class="block-fade-black" data-start="0" data-duration="1" data-track-index="0" data-transition-in="fade" data-transition-out="fade"></div>',
    css: '.block-fade-black { width: 1920px; height: 1080px; background: #000; }',
    thumbnail: '/blocks/fade-black.png',
    tags: ['transition', 'fade', 'black', 'classic'],
    author: 'HyperFrames',
  },
  {
    id: 'overlay-gradient',
    name: 'Gradient Overlay',
    category: 'overlay',
    description: 'Semi-transparent gradient overlay for text readability',
    html: '<div class="block-gradient-overlay" data-start="0" data-duration="10" data-track-index="2" data-z-index="10"></div>',
    css: '.block-gradient-overlay { position: absolute; inset: 0; background: linear-gradient(to top, rgba(0,0,0,0.8) 0%, transparent 50%); pointer-events: none; }',
    thumbnail: '/blocks/gradient-overlay.png',
    tags: ['overlay', 'gradient', 'text', 'readability'],
    author: 'HyperFrames',
  },
  {
    id: 'overlay-vignette',
    name: 'Vignette',
    category: 'overlay',
    description: 'Dark vignette around edges for cinematic feel',
    html: '<div class="block-vignette" data-start="0" data-duration="10" data-track-index="2" data-z-index="5"></div>',
    css: '.block-vignette { position: absolute; inset: 0; background: radial-gradient(ellipse at center, transparent 50%, rgba(0,0,0,0.6) 100%); pointer-events: none; }',
    thumbnail: '/blocks/vignette.png',
    tags: ['overlay', 'vignette', 'cinematic', 'dark'],
    author: 'HyperFrames',
  },
  {
    id: 'template-promo-video',
    name: 'Promo Video',
    category: 'template',
    description: 'Complete promo video template with intro, content, and CTA',
    html: '<div class="template-promo" data-start="0" data-duration="15" data-track-index="0"><section class="promo-intro" data-start="0" data-duration="3"><h1>Introducing</h1><h2>Product Name</h2></section><section class="promo-body" data-start="3" data-duration="8"><p>Key features and benefits listed here</p></section><section class="promo-cta" data-start="11" data-duration="4"><h2>Get Started Today</h2><button>Learn More</button></section></div>',
    css: '.template-promo { width: 1920px; height: 1080px; background: #09090b; color: white; } .promo-intro, .promo-body, .promo-cta { position: absolute; inset: 0; display: flex; flex-direction: column; align-items: center; justify-content: center; } .promo-intro h1 { font-size: 36px; opacity: 0.6; letter-spacing: 8px; } .promo-intro h2 { font-size: 80px; font-weight: 800; } .promo-body p { font-size: 32px; max-width: 800px; text-align: center; line-height: 1.6; } .promo-cta h2 { font-size: 56px; margin-bottom: 24px; } .promo-cta button { padding: 16px 48px; font-size: 24px; background: #8b5cf6; color: white; border: none; border-radius: 8px; }',
    thumbnail: '/blocks/promo-video.png',
    tags: ['template', 'promo', 'marketing', 'complete'],
    author: 'HyperFrames',
  },
  {
    id: 'template-presentation',
    name: 'Presentation Slide',
    category: 'template',
    description: 'Clean presentation slide with title and bullet points',
    html: '<div class="template-presentation" data-start="0" data-duration="5" data-track-index="0"><h1 class="slide-title">Slide Title</h1><ul class="slide-points"><li>First key point</li><li>Second key point</li><li>Third key point</li></ul></div>',
    css: '.template-presentation { width: 1920px; height: 1080px; background: #09090b; color: white; padding: 120px; } .slide-title { font-size: 64px; font-weight: 700; margin-bottom: 48px; border-left: 6px solid #8b5cf6; padding-left: 24px; } .slide-points { list-style: none; padding: 0; } .slide-points li { font-size: 32px; padding: 16px 0; border-bottom: 1px solid rgba(255,255,255,0.1); }',
    thumbnail: '/blocks/presentation.png',
    tags: ['template', 'presentation', 'slide', 'clean'],
    author: 'HyperFrames',
  },
];
